comment "Exported from Arsenal by JerkinMerkin";

comment "Remove existing items";
removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;

comment "Add containers";
_this forceAddUniform "rhs_uniform_FROG01_d";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_fieldDressing";};
_this addItemToUniform "ACE_morphine";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_quikclot";};
_this addItemToUniform "ACE_EarPlugs";
_this addItemToUniform "ACE_MapTools";
for "_i" from 1 to 4 do {_this addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_tourniquet";};
for "_i" from 1 to 2 do {_this addItemToUniform "ACE_CableTie";};
_this addItemToUniform "ACE_Flashlight_MX991";
_this addVest "rhsusf_spc_corpsman";
for "_i" from 1 to 2 do {_this addItemToVest "rhs_mag_m67";};
for "_i" from 1 to 2 do {_this addItemToVest "rhs_mag_an_m8hc";};
for "_i" from 1 to 4 do {_this addItemToVest "Chemlight_green";};
for "_i" from 1 to 6 do {_this addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag";};
_this addBackpack "rhsusf_assault_eagleaiii_coy";
for "_i" from 1 to 20 do {_this addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 15 do {_this addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 15 do {_this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_atropine";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_adenosine";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 5 do {_this addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 15 do {_this addItemToBackpack "ACE_packingBandage";};
_this addItemToBackpack "ACE_personalAidKit";
for "_i" from 1 to 2 do {_this addItemToBackpack "ACE_plasmaIV_250";};
_this addItemToBackpack "ACE_plasmaIV_500";
for "_i" from 1 to 4 do {_this addItemToBackpack "ACE_tourniquet";};
_this addHeadgear "rhsusf_lwh_helmet_marpatd";
_this addGoggles "FGN_CauR_Shemag_brown";

comment "Add weapons";
_this addWeapon "rhs_weap_m4a1_carryhandle_grip3";
_this addPrimaryWeaponItem "rhsusf_acc_anpeq15";
_this addPrimaryWeaponItem "rhsusf_acc_compm4";
_this addPrimaryWeaponItem "rhsusf_acc_grip3";

comment "Add items";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "TFAR_anprc152";

comment "Set identity";
_this setFace "WhiteHead_11";
_this setSpeaker "male04gre";
